# Generated by Django 3.2 on 2021-05-25 10:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_price', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Кінцева сумма')),
                ('final_count_of_items', models.PositiveIntegerField(default=0, verbose_name='Кількість всіх продуктів у корзині')),
                ('in_order', models.BooleanField(default=False)),
                ('for_anonymous_user', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='main.category')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Назва товару')),
                ('description', models.CharField(max_length=300, verbose_name='Опис товару')),
                ('slug', models.SlugField(unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Ціна')),
                ('photo', models.ImageField(upload_to='', verbose_name='Зображення')),
                ('pub_date', models.DateTimeField(verbose_name='Дата публікації')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.category')),
            ],
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.product')),
                ('age', models.CharField(max_length=75, verbose_name='Вік')),
                ('brand', models.CharField(blank=True, max_length=75, null=True, verbose_name='Бренд')),
            ],
            bases=('main.product',),
        ),
        migrations.CreateModel(
            name='Toys',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.product')),
                ('age', models.CharField(max_length=75, verbose_name='Вік')),
            ],
            bases=('main.product',),
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=75, verbose_name='Номер телефону')),
                ('adress', models.CharField(max_length=75, verbose_name='Домашній адрес')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CartProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveIntegerField(default=1)),
                ('final_price', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Кінцева сумма')),
                ('basket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.cart')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.product')),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.customer'),
        ),
        migrations.AddField(
            model_name='cart',
            name='product_in_cart',
            field=models.ManyToManyField(blank=True, to='main.CartProduct', verbose_name='Продукти в корзині'),
        ),
        migrations.CreateModel(
            name='Girl',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.product')),
                ('sizon', models.CharField(max_length=125, verbose_name='Сезон')),
                ('size', models.CharField(max_length=75, verbose_name='Розмір')),
                ('age', models.CharField(max_length=75, verbose_name='Вік')),
                ('brand', models.CharField(blank=True, max_length=75, null=True, verbose_name='Бренд')),
                ('material', models.CharField(blank=True, max_length=75, null=True, verbose_name='Состав')),
                ('father', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='main.girl')),
            ],
            bases=('main.product',),
        ),
        migrations.CreateModel(
            name='Boy',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.product')),
                ('sizon', models.CharField(max_length=125, verbose_name='Сезон')),
                ('size', models.CharField(max_length=75, verbose_name='Розмір')),
                ('age', models.CharField(max_length=75, verbose_name='Вік')),
                ('brand', models.CharField(blank=True, max_length=75, null=True, verbose_name='Бренд')),
                ('material', models.CharField(blank=True, max_length=75, null=True, verbose_name='Состав')),
                ('father', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='main.boy')),
            ],
            bases=('main.product',),
        ),
        migrations.CreateModel(
            name='Baby',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.product')),
                ('sizon', models.CharField(max_length=125, verbose_name='Сезон')),
                ('size', models.CharField(max_length=75, verbose_name='Розмір')),
                ('age', models.CharField(max_length=75, verbose_name='Вік')),
                ('brand', models.CharField(blank=True, max_length=75, null=True, verbose_name='Бренд')),
                ('material', models.CharField(blank=True, max_length=75, null=True, verbose_name='Состав')),
                ('father', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='main.baby')),
            ],
            bases=('main.product',),
        ),
    ]
