# Generated by Django 3.2 on 2021-05-27 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=75, verbose_name="Ім'я")),
                ('last_name', models.CharField(max_length=75, verbose_name='Прізвище')),
                ('phone', models.CharField(max_length=75, verbose_name='Телефон')),
                ('adress', models.CharField(blank=True, max_length=550, null=True, verbose_name='Адрес доставки')),
                ('status', models.CharField(choices=[('is_ready', 'Замовлення готове'), ('new', 'Нове зомовлення'), ('in_progress', 'Замовлення обробляється'), ('completed', 'Замовлення виконане')], default='new', max_length=225, verbose_name='Статус замовлення')),
                ('buying_type', models.CharField(choices=[('self', 'Самовивіз'), ('delivery', 'Доставка')], default='self', max_length=225, verbose_name='Тип замовлення')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Коментарій до замовлення')),
                ('created_data', models.DateTimeField(auto_now=True, verbose_name='Дата створення замовлення')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.customer', verbose_name='Замовник')),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='orders',
            field=models.ManyToManyField(related_name='related_customer', to='main.Order', verbose_name='Замовлення покупця'),
        ),
    ]
