# Generated by Django 3.2 on 2021-05-01 13:43

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_category_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boy',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.product')),
                ('color', colorfield.fields.ColorField(blank=True, default=None, max_length=18, null=True)),
            ],
            bases=('main.product',),
        ),
    ]
