# Generated by Django 3.2 on 2021-05-29 09:30

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210528_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.customer', verbose_name='Власник кошика'),
        ),
        migrations.AlterField(
            model_name='order',
            name='buying_type',
            field=models.CharField(choices=[('delivery', 'Доставка'), ('self', 'Самовивіз')], default='self', max_length=225, verbose_name='Тип замовлення'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(default=datetime.datetime(2021, 5, 29, 9, 30, 21, 890719, tzinfo=utc), verbose_name='Бажана дата отримання замовлення'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Нове зомовлення'), ('is_ready', 'Замовлення готове'), ('in_progress', 'Замовлення обробляється'), ('completed', 'Замовлення виконане')], default='new', max_length=225, verbose_name='Статус замовлення'),
        ),
    ]
