# Generated by Django 3.2 on 2021-05-06 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210503_1315'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boy',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.product')),
                ('sizon', models.CharField(max_length=125, verbose_name='Сезон')),
                ('size', models.TextField(verbose_name='Розмір')),
                ('age', models.CharField(max_length=75, verbose_name='Вік')),
                ('brand', models.CharField(blank=True, max_length=75, null=True, verbose_name='Бренд')),
                ('material', models.CharField(blank=True, max_length=75, null=True, verbose_name='Состав')),
            ],
            bases=('main.product',),
        ),
        migrations.CreateModel(
            name='Girl',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.product')),
                ('sizon', models.CharField(max_length=125, verbose_name='Сезон')),
                ('size', models.TextField(verbose_name='Розмір')),
                ('age', models.CharField(max_length=75, verbose_name='Вік')),
                ('brand', models.CharField(blank=True, max_length=75, null=True, verbose_name='Бренд')),
                ('material', models.CharField(blank=True, max_length=75, null=True, verbose_name='Состав')),
            ],
            bases=('main.product',),
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.product')),
                ('age', models.CharField(max_length=75, verbose_name='Вік')),
                ('brand', models.CharField(blank=True, max_length=75, null=True, verbose_name='Бренд')),
            ],
            bases=('main.product',),
        ),
        migrations.CreateModel(
            name='Toys',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.product')),
                ('age', models.CharField(max_length=75, verbose_name='Вік')),
            ],
            bases=('main.product',),
        ),
        migrations.RenameModel(
            old_name='BoyGirlBaby',
            new_name='Baby',
        ),
    ]
