# Generated by Django 3.2 on 2021-05-29 10:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210529_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='buying_type',
            field=models.CharField(choices=[('self', 'Самовивіз'), ('delivery', 'Доставка')], default='self', max_length=225, verbose_name='Тип замовлення'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(default=datetime.datetime(2021, 5, 29, 10, 18, 13, 78188, tzinfo=utc), verbose_name='Бажана дата отримання замовлення'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('is_ready', 'Замовлення готове'), ('new', 'Нове зомовлення'), ('in_progress', 'Замовлення обробляється'), ('completed', 'Замовлення виконане')], default='new', max_length=225, verbose_name='Статус замовлення'),
        ),
    ]
