# Generated by Django 3.2 on 2021-05-30 10:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210529_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='adress',
            field=models.CharField(blank=True, max_length=75, null=True, verbose_name='Домашній адрес'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(blank=True, max_length=75, null=True, verbose_name='Номер телефону'),
        ),
        migrations.AlterField(
            model_name='order',
            name='buying_type',
            field=models.CharField(choices=[('delivery', 'Доставка'), ('self', 'Самовивіз')], default='self', max_length=225, verbose_name='Тип замовлення'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(default=datetime.datetime(2021, 5, 30, 10, 7, 36, 530885, tzinfo=utc), verbose_name='Бажана дата отримання замовлення'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Нове зомовлення'), ('in_progress', 'Замовлення обробляється'), ('is_ready', 'Замовлення готове'), ('completed', 'Замовлення виконане')], default='new', max_length=225, verbose_name='Статус замовлення'),
        ),
    ]
