# Generated by Django 3.2 on 2021-05-30 11:19

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210530_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.customer', verbose_name='Власник кошика'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(default=datetime.datetime(2021, 5, 30, 11, 19, 32, 483195, tzinfo=utc), verbose_name='Бажана дата отримання замовлення'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('completed', 'Замовлення виконане'), ('new', 'Нове зомовлення'), ('in_progress', 'Замовлення обробляється'), ('is_ready', 'Замовлення готове')], default='new', max_length=225, verbose_name='Статус замовлення'),
        ),
    ]
