# Generated by Django 3.2 on 2021-05-17 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20210517_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productattributevalue',
            name='value',
            field=models.CharField(max_length=150),
        ),
    ]
