# Generated by Django 3.2 on 2021-05-18 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_productattributevalue_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='SizeField',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.product')),
                ('product_size', models.PositiveIntegerField()),
                ('prod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='main.product')),
            ],
            bases=('main.product',),
        ),
    ]
