# Generated by Django 3.2 on 2021-05-18 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_sizefield'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SizeField',
        ),
    ]
