# Generated by Django 3.2 on 2021-05-18 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_sizefield'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attributevariant',
            name='attribute',
        ),
        migrations.RemoveField(
            model_name='productattributevalue',
            name='attribute',
        ),
        migrations.RemoveField(
            model_name='productattributevalue',
            name='variant',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='product',
        ),
        migrations.RemoveField(
            model_name='sizefield',
            name='prod',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_attribute',
        ),
        migrations.AddField(
            model_name='baby',
            name='father',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='main.baby'),
        ),
        migrations.AddField(
            model_name='boy',
            name='father',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='main.boy'),
        ),
        migrations.AddField(
            model_name='girl',
            name='father',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='main.girl'),
        ),
        migrations.DeleteModel(
            name='Attribute',
        ),
        migrations.DeleteModel(
            name='AttributeVariant',
        ),
        migrations.DeleteModel(
            name='ProductAttributeValue',
        ),
        migrations.DeleteModel(
            name='ProductVariant',
        ),
        migrations.DeleteModel(
            name='SizeField',
        ),
    ]
