# Generated by Django 3.2 on 2021-05-19 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20210518_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartproduct',
            name='sizes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='baby',
            name='size',
            field=models.PositiveIntegerField(verbose_name='Розмір'),
        ),
        migrations.AlterField(
            model_name='boy',
            name='size',
            field=models.PositiveIntegerField(verbose_name='Розмір'),
        ),
        migrations.AlterField(
            model_name='girl',
            name='size',
            field=models.PositiveIntegerField(verbose_name='Розмір'),
        ),
    ]
