# Generated by Django 3.2 on 2021-05-20 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_remove_cartproduct_sizes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baby',
            name='size',
            field=models.CharField(max_length=75, verbose_name='Розмір'),
        ),
        migrations.AlterField(
            model_name='boy',
            name='size',
            field=models.CharField(max_length=75, verbose_name='Розмір'),
        ),
        migrations.AlterField(
            model_name='girl',
            name='size',
            field=models.CharField(max_length=75, verbose_name='Розмір'),
        ),
    ]
