# Generated by Django 3.2 on 2021-05-20 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_product_pub_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='pub_date',
        ),
    ]
